version: 2
jobs:
  produce_file:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/project
    steps:
      - checkout
      - 
        attach_workspace:
          at: ~/project
      - 
        run: |
          echo "hello world" > hello_world.txt
          exit 0 # CircleCI hangs if I remove this
      - 
        persist_to_workspace:
          root: .
          paths:
            - hello_world.txt
  consume_file:
    docker:
      - image: circleci/ruby:2.4.1
    working_directory: ~/project
    steps:
      - checkout
      - 
        attach_workspace:
          at: ~/project
      - 
        run: |
          ls hello_world.txt
          cat hello_world.txt
          exit 0
workflows:
  version: 2
  workspace_test:
    jobs:
      - produce_file
      - 
        consume_file:
          requires:
            - produce_file
