version: 2
jobs:
  produce_file:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - 
        run: |
          mkdir -p /tmp/circlecitest && echo "hello world" > /tmp/circlecitest/hello_world.txt
      - 
        persist_to_workspace:
          root: /tmp/circlecitest
          paths:
            - hello_world.txt
  consume_file:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - 
        attach_workspace:
          at: /tmp/circlecitest
      - 
        run: |
          ls /tmp/workspace/hello_world.txt
workflows:
  version: 2
  workspace_test:
    jobs:
      - produce_file
      - 
        consume_file:
          requires:
            - produce_file
