version: 2
jobs:
  job_1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: exit 0
  job_2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello $MY_NAME"
      - run: exit 0
workflows:
  version: 2
  wf_1:
    jobs:
      - job_1
  wf_all:
    jobs:
      - job_1
      - 
        job_2:
          context: test-context
          requires: 
            - job_1

  
