version: 2
jobs:
  hello_world:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - 
        run: 
          name: hello world
          command: |
            echo "hello world"
            exit 0
  profit_and_loss:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: ruby -e "ENV['NET_INCOME'].to_i>0?(exit 0):(exit 1)"
workflows:
  version: 2
  wf_unsuccessful_company:
    jobs:
      - 
        profit_and_loss:
          context: unsuccessful_company
