version: 2
jobs:
  build_job_1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: exit 33
workflows:
  version: 2
  build:
    jobs:
      - build_job_1
  
