version: 2
jobs:
  job_1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: exit 0
  job_2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: if [ -z "$MY_NAME" ]; then exit 1; fi
      - run: exit 0
workflows:
  version: 2
  wf_1:
    jobs:
      - job_1
  wf_all:
    jobs:
      - job_1
      - 
        job_2:
          requires: 
            - job_1

  
